### ISSUE TITLE
Error in the event based feature's boostraping

### ISSUE THREAD

**Issue by John71509** [uzh-rpg/rpg_eklt#2]
Hello @danielgehrig18 ,

I think that there is an error in the `bootstrapFeatureEvents()` method.
In fact, at line 407 you are multiplying the event patch with the frame's gradient in the X direction but it should be the one in the Y direction.
`double s_I_yt = cv::sum(I_x.mul(event_frame))[0];` should rather be
`double s_I_yt = cv::sum(I_y.mul(event_frame))[0];` 

Best regards,
Jonathan.

**Comment by danielgehrig18** [comment]
Yes of course. This will be fixed.

**Comment by danielgehrig18** [comment]
Has been fixed in the most recent commit
