### ISSUE TITLE
Question about the implementation

### ISSUE THREAD

**Issue by abylikhsanov** [uzh-rpg/rpg_eklt#4]
Hi,

I was reading the UltimateSLAM [paper](http://rpg.ifi.uzh.ch/ultimateslam.html) and they have referenced your work multiple times but I had an impression that this code is only for the event + IMU and after browsing your code you do actually use both events and frames from the camera. Is this an extension of your previous work?

**Comment by knelk** [comment]
Hi, 

You might have mixed up the papers. This code is implementing the publication "EKLT: Asynchronous Photometric Feature Tracking Using Events and Frames" (D. Gehrig et al.), where they extract features on the frames and track them using events. 

Where does the Ultimate SLAM paper reference to eklt?
