### ISSUE TITLE
I think there is some bug in code

### ISSUE THREAD

**Issue by yejun1204** [uzh-rpg/rpg_eklt#6]
while studying your code

I found that even though FLAGS_bootstrap is set as "klt"

in tracker.cpp processEvents()

if (updateFirstImageBeforeTime(most_current_time_, current_image_it_)) // enter if new image found
        {
            VLOG(1)<<"new image found";
            VLOG(1)<<FLAGS_bootstrap;
            VLOG(1)<<(FLAGS_bootstrap=="klt");

            // bootstrap patches that need to be due to new image
            if (FLAGS_bootstrap == "klt")
            {
                VLOG(1)<<"boot strap klt";
                bootstrapAllPossiblePatches(patches_, current_image_it_);
            }

**VLOG(1)<<(FLAGS_bootstrap=="klt"); is printed as '0' and bootstrapAllPossiblePatches could not entered**

**Comment by gogojjh** [comment]
I have met the same issue. It may be caused by different versions of GFLAGS. It fix it by modifing the ```="klt"``` as ```=klt``` in ```config/eklt.conf```.

**Comment by yejun1204** [comment]
> I have met the same issue. It may be caused by different versions of GFLAGS. It fix it by modifing the `="klt"` as `=klt` in `config/eklt.conf`.

thank you problem is solved
