### ISSUE TITLE
Tracking features from simulated data

### ISSUE THREAD

**Issue by BonJovi1** [uzh-rpg/rpg_eklt#7]
Hi @danielgehrig18 

Thanks a lot for your code! I was trying to use EKLT to track features using simulated data from RPG's [Event Camera Simulator](https://github.com/uzh-rpg/rpg_esim). I got your code to work on the `boxes_6dof` scene from the [event camera dataset](http://rpg.ifi.uzh.ch/davis_data.html). But unfortunately, the EKLT code doesn't seem to work on the `bag` file outputted by the simulator. When I do `rosbag play simulated_data.bag`, it's unable to recognise it and still says: _Waiting for the first image_

Any idea why this may be happening? Is it possible that the format the event simulator stores the data in is NOT the same as the format followed by the event camera dataset? 
For instance, when I play the simulated file with `rosbag play simulated_data.bag`, and then list out the topics with `rostopic list`, I get the following:
```
/cam0/camera_info
/cam0/events
/cam0/image_corrupted
/cam0/image_raw
/clock
/dvs/events
/dvs/image_raw
/rosout
/rosout_agg
```
But when I play the `boxes_6dof.bag` file from the event camera dataset, and list out the topics, I notice some variations:
```
/clock
/dvs/camera_info
/dvs/events
/dvs/image_raw
/dvs/imu
/optitrack/davis
/rosout
/rosout_agg
```
Sorry for the long query. Would be really grateful for your advice! :) 

Thank you,
Abhinav

**Comment by danielgehrig18** [comment]
Hi Abhinav,

It looks like you need to change the topic names in the .launch file to
correspond with the topics in the similated bag. Then it should recognize
them. Let me know if that works for you.

**Comment by BonJovi1** [comment]
Hi Daniel,

Thank you so much, this worked! Silly me, I should've checked the .launch file. 
Just had a couple more follow-up questions. 

(1) I tried to track features for static scenes exhibiting human motion. It seems to track some features in an area where there is no motion taking place. For instance, in the top-left corner of this image, some features are being tracked. But those pixels aren't moving, it's only the girl in the middle who's skipping. Could you please advise me on how to ameliorate this issue?

<img width="450" alt="output" src="https://user-images.githubusercontent.com/32260656/104112588-98085180-5316-11eb-8323-267d192f66b5.png">

(2) Another thing I noticed is that, there seem to be less features being tracked in later frames of the video. When I run the code, It starts off with _tracking 60 features and keeps reducing by one until it reaches 0. Could you please elaborate on what this exactly means? 

Thanks a lot! 
Abhinav

**Comment by BonJovi1** [comment]
Hi @danielgehrig18 
Sorry for troubling you again. Very eagerly awaiting your response, whenever you're free! 

Thank you,
Abhinav

**Comment by danielgehrig18** [comment]
Hi Abhinav, sorry for the delay. Corners at pixels that are not moving do
not trigger events, and so they are never updated. This is in line with the
asynchronous operation principle our work is based on. The current settings
were chosen for evaluation and basically never initialize new features. To
do this, the parameter 'min_num_corners' needs to set to a higher value
than 0, then the tracker will never go below that number. Hope I could be
of help.

**Comment by BonJovi1** [comment]
Hi Daniel, 
Thank you so much! You're right, I'm not updating the corner pixels. I'll try out your suggestion to alter the `min_num_corners` parameter. Hopefully that ought to do the trick, will let you know asap!  

Thanks a bunch,
Abhinav

**Comment by BonJovi1** [comment]
Hi Daniel,
Thanks a lot for your help! I set `min_num_corners` to a higher value and now the tracks are much more dense and prominent. Thank you very much for your advice, I shall go ahead and close this issue
Abhinav

**Comment by danielgehrig18** [comment]
Great, good to hear it worked for you :)
