### ISSUE TITLE
Excess error when testing with boxes_6dof.bag

### ISSUE THREAD

**Issue by zhuguoliang** [uzh-rpg/rpg_eklt#8]
Hi community!

I've followed the steps and merged running of rpg_eklt and rpg_feature_tracking_analysis in  the same environment.

The test result I've got is shown in following picture, I was expecting a much lower error after 6s.

Please give me a hint here on how could I get the same result in README. 

Thks! 

![image](https://user-images.githubusercontent.com/9863649/122729452-c4ec6780-d2ab-11eb-8348-cec10b929cf6.png)

**Comment by li10141110** [comment]
After 6s they lost the object so error goes up.

**Comment by li10141110** [comment]
Hi, do you know any Chinese study group regarding event camera or visual servoing? My wechat is CV-NLP. Hope we can have talk.
